---
output: html_document
---

#### About 

This web application is built for the individualized prediction of lung function decline based on 3 models:
1. Prediction of future lung function decline based on baseline FEV1
2. Prediction of future lung function decline based on baseline FEV1 and patients' clinical characteristics
3. Prediction of future lung function decline based on baseline FEV1, patients' clinical characteristics, and 1-year prior history of FEV1. Interested model as well as other patient's characteristics can be selected below for seeing the predicted rate of lung function decline.
                         
#### Credits
Individualized FEV1 predictor is created by Zafar Zafari, Ainsleigh Hill, Jane Krot, and Amin Adibi. 

Please cite this paper when using the results of this web application:
This web application is based on the paper entitled 'Individualised prediction of lung function decline in COPD'.", br(), "Authors: Zafar Zafari, Don D. Sin, Dirkje S. Postma, Claes-Goran Lofdahl, Judith Vonk, Stirling Bryan, Rahman Khakban, S.F. Paul Man, Donald Tashkin, Robert A. Wise, John E. Connett, Bruce McManus, MD, Raymond Ng, Zsuszanna Hollander, Mohsen Sadatsafavi.
